---
site_name: PHP Compatinfo
site_url: https://llaville.github.io/php-compatinfo/7.2
repo_url: https://github.com/llaville/php-compatinfo # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository
site_author: Laurent Laville
edit_uri: "" # hide edit button -- https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#edit-button
theme:
    name: material
    palette: # Color palette toggle -- https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
        # editorconfig-checker-disable
        - scheme: default
          primary: lime
          toggle:
              icon: material/lightbulb-outline
              name: Switch to dark mode
        - scheme: slate
          toggle:
              icon: material/lightbulb
              name: Switch to light mode
        # editorconfig-checker-enable
    features:
        - navigation.instant # Instant loading -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
        - navigation.tabs # Navigation tabs -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
        - navigation.indexes # Section index pages -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
        - navigation.top # Back-To-Top button -- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
markdown_extensions:
    - pymdownx.highlight # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
    - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences
nav:
    - "Home": README.md
    - "Getting-Started": installation.md
    - "Components": components/README.md
    - "Configurations": configs/README.md
    - "Conditional Code": conditional-code/README.md
    - "Exclusions": exclusions/README.md
    - "Architecture": architecture/README.md
